In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\madas\Downloads\car_df_EDA.csv")
df

Unnamed: 0.1  Unnamed: 0         make fuel_type aspiration num_of_doors  \
0               0           1  alfa-romero       gas        std          two   
1               1           2  alfa-romero       gas        std          two   
2               2           3  alfa-romero       gas        std          two   
3               3           4         audi       gas        std         four   
4               4           5         audi       gas        std         four   
..            ...         ...          ...       ...        ...          ...   
203           203         204        volvo    diesel      turbo         four   
204           204         205        volvo       gas      turbo         four   
205           202         203        volvo       gas        std         four   
206           203         204        volvo    diesel      turbo         four   
207           204         205        volvo       gas      turbo         four   

      body_style drive_wheels engine_location  wheel_base  ...  engine_type  \
0    convertible          rwd           front        88.6  ...         dohc   
1    convertible          rwd           front        88.6  ...         dohc   
2      hatchback          rwd           front        94.5  ...         ohcv   
3          sedan          fwd           front        99.8  ...          ohc   
4          sedan          4wd           front        99.4  ...          ohc   
..           ...          ...             ...         ...  ...          ...   
203        sedan          rwd           front       109.1  ...          ohc   
204        sedan          rwd           front       109.1  ...          ohc   
205        sedan          rwd           front       109.1  ...         ohcv   
206        sedan          rwd           front       109.1  ...          ohc   
207        sedan          rwd           front       109.1  ...          ohc   

     num_of_cylinders  engine_size  fuel_system compression_ratio horsepower  \
0                four        130.0         mpfi               9.0        111   
1                four        130.0         mpfi               9.0        111   
2                 six        152.0         mpfi               9.0        154   
3                four        109.0         mpfi              10.0        102   
4                five        136.0         mpfi               8.0        115   
..                ...          ...          ...               ...        ...   
203               six        145.0          idi              23.0        106   
204              four        141.0         mpfi               9.5        114   
205               six        173.0         mpfi               8.8        134   
206               six        145.0          idi              23.0        106   
207              four        141.0         mpfi               9.5        114   

     peak_rpm city_mpg  highway_mpg  price  
0        5000       21           27  13495  
1        5000       21           27  16500  
2        5000       19           26  16500  
3        5500       24           30  13950  
4        5500       18           22  17450  
..        ...      ...          ...    ...  
203      4800       26           27    NaN  
204      5400       19           25  22625  
205      5500       18           23  21485  
206      4800       26           27    NaN  
207      5400       19           25  22625  

[208 rows x 24 columns]

### work on above dataset...perform all data cleaning methods.

In [3]:
df.drop(['Unnamed: 0.1','Unnamed: 0'],axis = 1,inplace = True)

In [4]:
df.head(3)

make fuel_type aspiration num_of_doors   body_style drive_wheels  \
0  alfa-romero       gas        std          two  convertible          rwd   
1  alfa-romero       gas        std          two  convertible          rwd   
2  alfa-romero       gas        std          two    hatchback          rwd   

  engine_location  wheel_base  length  width  ...  engine_type  \
0           front        88.6   168.8   64.1  ...         dohc   
1           front        88.6   168.8   64.1  ...         dohc   
2           front        94.5   171.2   65.5  ...         ohcv   

   num_of_cylinders engine_size fuel_system  compression_ratio horsepower  \
0              four       130.0        mpfi                9.0        111   
1              four       130.0        mpfi                9.0        111   
2               six       152.0        mpfi                9.0        154   

   peak_rpm city_mpg highway_mpg  price  
0      5000       21          27  13495  
1      5000       21          27  16500  
2      5000       19          26  16500  

[3 rows x 22 columns]

In [5]:
def repl(n):
    if n == '?':
        return np.nan
    else :
        return n

In [9]:
df['make'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [10]:
df['fuel_type'].unique()

array(['gas', 'diesel'], dtype=object)

In [11]:
df['aspiration'].unique()

array(['std', 'turbo'], dtype=object)

In [12]:
df['num_of_doors'].unique()

array(['two', 'four', '?'], dtype=object)

In [14]:
df['num_of_doors'] = df['num_of_doors'].apply(repl)

In [15]:
df['body_style'].unique()

array(['convertible', 'hatchback', 'sedan', 'wagon', 'hardtop'],
      dtype=object)

In [16]:
df['drive_wheels'].unique()

array(['rwd', 'fwd', '4wd'], dtype=object)

In [17]:
df['engine_location'].unique()

array(['front', 'rear'], dtype=object)

In [18]:
df['wheel_base'].unique()

array([ 88.6,  94.5,  99.8,  99.4, 105.8,  99.5, 101.2,   nan, 103.5,
       110. ,  88.4,  93.7, 103.3,  95.9,  86.6,  96.5,  94.3,  96. ,
       113. , 102. ,  93.1,  95.3,  98.8, 104.9, 106.7, 115.6,  96.6,
       120.9, 112. , 102.7,  93. ,  96.3,  95.1,  97.2, 100.4,  91.3,
        99.2, 107.9, 114.2, 108. ,  89.5,  98.4,  96.1,  99.1,  93.3,
        97. ,  96.9,  95.7, 102.4, 102.9, 104.5,  97.3, 104.3, 109.1])

In [19]:
df['length'].unique()

array([168.8, 171.2, 176.6, 177.3, 192.7, 178.2, 176.8, 189. , 193.8,
       197. , 141.1, 155.9, 158.8, 157.3, 174.6, 173.2, 144.6, 150. ,
       163.4, 157.1, 167.5, 175.4, 169.1, 170.7, 172.6, 199.6, 191.7,
       159.1, 166.8, 169. , 177.8, 175. , 190.9, 187.5, 202.6, 180.3,
       208.1, 199.2, 178.4, 173. , 172.4, 165.3, 170.2, 165.6, 162.4,
       173.4, 181.7, 184.6, 178.5, 186.7, 198.9, 167.3, 168.9, 175.7,
       181.5, 186.6, 156.9, 157.9, 172. , 173.5, 173.6, 158.7, 169.7,
       166.3, 168.7, 176.2, 175.6, 183.5, 187.8, 171.7, 159.3, 165.7,
       180.2, 183.1, 188.8])

In [20]:
df['width'].unique()

array([64.1, 65.5, 66.2, 66.4, 66.3, 71.4, 67.9, 64.8, 66.9, 70.9, 60.3,
       63.6, 63.8, 64.6, 63.9, 64. , 65.2, 62.5, 66. , 61.8, 69.6, 70.6,
       64.2, 65.7, 66.5, 66.1, 70.3, 71.7, 70.5, 72. , 68. , 64.4, 65.4,
       68.4, 68.3, 65. , 72.3, 66.6, 63.4, 65.6, 67.7, 67.2, 68.9, 68.8])

In [22]:
df['height'].unique()

array([48.8, 52.4, 54.3, 53.1, 55.7, 55.9, 52. , 53.7, 56.3, 53.2, 50.8,
       50.6, 59.8, 50.2, 52.6, 54.5, 58.3, 53.3, 54.1, 51. , 53.5, 51.4,
       52.8, 47.8, 49.6, 55.5, 54.4, 56.5, 58.7, 54.9, 56.7, 55.4, 54.8,
       49.4, 51.6, 54.7, 55.1, 56.1, 49.7, 56. , 50.5, 55.2, 52.5, 53. ,
       59.1, 53.9, 55.6, 56.2, 57.5])

In [23]:
df['curb_weight'].unique()

array([2548, 2823, 2337, 2824, 2507, 2844, 2954, 3086, 3053, 2395, 2710,
       2765, 3055, 3230, 3380, 3505, 1488, 1874, 1909, 1876, 2128, 1967,
       1989, 2191, 2535, 2811, 1713, 1819, 1837, 1940, 1956, 2010, 2024,
       2236, 2289, 2304, 2372, 2465, 2293, 2734, 4066, 3950, 1890, 1900,
       1905, 1945, 1950, 2380, 2385, 2500, 2410, 2443, 2425, 2670, 2700,
       3515, 3750, 3495, 3770, 3740, 3685, 3900, 3715, 2910, 1918, 1944,
       2004, 2145, 2370, 2328, 2833, 2921, 2926, 2365, 2405, 2403, 1889,
       2017, 1938, 1951, 2028, 1971, 2037, 2008, 2324, 2302, 3095, 3296,
       3060, 3071, 3139, 3020, 3197, 3430, 3075, 3252, 3285, 3485, 3130,
       2818, 2778, 2756, 2800, 3366, 2579, 2460, 2658, 2695, 2707, 2758,
       2808, 2847, 2050, 2120, 2240, 2190, 2340, 2510, 2290, 2455, 2420,
       2650, 1985, 2040, 2015, 2280, 3110, 2081, 2109, 2275, 2094, 2122,
       2140, 2169, 2204, 2265, 2300, 2540, 2536, 2551, 2679, 2714, 2975,
       2326, 2480, 2414, 2458, 2976, 3016, 3131, 31

In [24]:
df['engine_type'].unique()

array(['dohc', 'ohcv', 'ohc', 'l', 'rotor', nan, 'ohcf', 'dohcv'],
      dtype=object)

In [25]:
df['num_of_cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [27]:
df['engine_size'].unique()

array([130., 152., 109., 136., 131., 108., 164., 209.,  61.,  90.,  98.,
       122., 156.,  92.,  79., 110.,  nan, 111., 119., 258., 326.,  91.,
        70.,  80., 140., 134., 183., 234., 308., 304.,  97., 103., 120.,
       181., 151., 194., 203., 132., 121., 146., 171., 161., 141., 173.,
       145.])

In [28]:
df['fuel_system'].unique()

array(['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi'],
      dtype=object)

In [29]:
df['compression_ratio'].unique()

array([ 9.  , 10.  ,  8.  ,  8.5 ,  8.3 ,  7.  ,  8.8 ,  9.5 ,  9.6 ,
        9.41,  9.4 ,  7.6 ,  9.2 , 10.1 ,  9.1 ,  8.1 , 11.5 ,  8.6 ,
       22.7 , 22.  , 21.5 ,  7.5 , 21.9 ,  7.8 ,  8.4 , 21.  ,  8.7 ,
        9.31,  9.3 ,  7.7 , 22.5 , 23.  ])

In [32]:
df['horsepower'] = df['horsepower'].apply(repl)

In [26]:
df.columns

Index(['make', 'fuel_type', 'aspiration', 'num_of_doors', 'body_style',
       'drive_wheels', 'engine_location', 'wheel_base', 'length', 'width',
       'height', 'curb_weight', 'engine_type', 'num_of_cylinders',
       'engine_size', 'fuel_system', 'compression_ratio', 'horsepower',
       'peak_rpm', 'city_mpg', 'highway_mpg', 'price'],
      dtype='object')

In [34]:
df['peak_rpm'] = df['peak_rpm'].apply(repl)

In [36]:
df['city_mpg'].unique()

array([21, 19, 24, 18, 17, 16, 23, 20, 15, 47, 38, 37, 31, 49, 30, 27, 25,
       13, 26, 36, 22, 14, 45, 28, 32, 35, 34, 29, 33], dtype=int64)

In [37]:
df['highway_mpg'].unique()

array([27, 26, 30, 22, 25, 20, 29, 28, 53, 43, 41, 38, 24, 54, 42, 34, 33,
       31, 19, 17, 23, 32, 39, 18, 16, 37, 50, 36, 47, 46], dtype=int64)

In [39]:
df['price'] = df['price'].apply(repl)

### Missing values

In [41]:
df.isna().sum()

make                 0
fuel_type            0
aspiration           0
num_of_doors         2
body_style           0
drive_wheels         0
engine_location      0
wheel_base           2
length               0
width                0
height               0
curb_weight          0
engine_type          1
num_of_cylinders     0
engine_size          2
fuel_system          0
compression_ratio    0
horsepower           2
peak_rpm             2
city_mpg             0
highway_mpg          0
price                8
dtype: int64

In [44]:
import warnings
warnings.filterwarnings('ignore')

In [45]:
df['num_of_doors'].fillna(method = 'ffill',inplace = True)

In [ ]:
df['wheel_base'].fillna(method = 'ffill',inplace = True)

In [50]:
df['wheel_base'].fillna(df['wheel_base'].mean(),inplace = True)

In [53]:
df['engine_type'].fillna(method = 'bfill',inplace = True)

In [59]:
df['engine_size'].fillna(df['engine_size'].mean(),inplace = True)

In [72]:
df['horsepower'].fillna(df['horsepower'].median(),inplace = True)

In [77]:
df['peak_rpm'].fillna(df['peak_rpm'].median(),inplace = True)

In [82]:
df['price'].fillna(df['price'].median(),inplace = True)

In [83]:
df.isna().sum()

make                 0
fuel_type            0
aspiration           0
num_of_doors         0
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_of_cylinders     0
engine_size          0
fuel_system          0
compression_ratio    0
horsepower           0
peak_rpm             0
city_mpg             0
highway_mpg          0
price                0
dtype: int64

## Duplicate values

In [85]:
df.duplicated().sum()

3

In [86]:
df.drop_duplicates(keep = 'first',inplace = True)

In [87]:
df.duplicated().sum()

0

## outliers

In [89]:
df.head()

make fuel_type aspiration num_of_doors   body_style drive_wheels  \
0  alfa-romero       gas        std          two  convertible          rwd   
1  alfa-romero       gas        std          two  convertible          rwd   
2  alfa-romero       gas        std          two    hatchback          rwd   
3         audi       gas        std         four        sedan          fwd   
4         audi       gas        std         four        sedan          4wd   

  engine_location  wheel_base  length  width  ...  engine_type  \
0           front        88.6   168.8   64.1  ...         dohc   
1           front        88.6   168.8   64.1  ...         dohc   
2           front        94.5   171.2   65.5  ...         ohcv   
3           front        99.8   176.6   66.2  ...          ohc   
4           front        99.4   176.6   66.4  ...          ohc   

   num_of_cylinders engine_size fuel_system  compression_ratio horsepower  \
0              four       130.0        mpfi                9.0        111   
1              four       130.0        mpfi                9.0        111   
2               six       152.0        mpfi                9.0        154   
3              four       109.0        mpfi               10.0        102   
4              five       136.0        mpfi                8.0        115   

   peak_rpm city_mpg highway_mpg  price  
0      5000       21          27  13495  
1      5000       21          27  16500  
2      5000       19          26  16500  
3      5500       24          30  13950  
4      5500       18          22  17450  

[5 rows x 22 columns]

In [90]:
q1 = df['wheel_base'].quantile(0.25)

In [92]:
q3 = df['wheel_base'].quantile(0.75) 

In [93]:
IQR = q3 - q1
IQR

7.900000000000006

In [94]:
low = q1 - 1.5*IQR
upp = q3 + 1.5*IQR

In [97]:
df[(df['wheel_base'] < low)|(df['wheel_base']>upp)]

make fuel_type aspiration num_of_doors body_style drive_wheels  \
70  mercedes-benz    diesel      turbo         four      sedan          rwd   
71  mercedes-benz       gas        std         four      sedan          rwd   
73  mercedes-benz       gas        std         four      sedan          rwd   

   engine_location  wheel_base  length  width  ...  engine_type  \
70           front       115.6   202.6   71.7  ...          ohc   
71           front       115.6   202.6   71.7  ...         ohcv   
73           front       120.9   208.1   71.7  ...         ohcv   

    num_of_cylinders engine_size fuel_system  compression_ratio horsepower  \
70              five       183.0         idi               21.5        123   
71             eight       234.0        mpfi                8.3        155   
73             eight       308.0        mpfi                8.0        184   

    peak_rpm city_mpg highway_mpg  price  
70      4350       22          25  31600  
71      4750       16          18  34184  
73      4500       14          16  40960  

[3 rows x 22 columns]

In [98]:
cond = (df['wheel_base'] < low)|(df['wheel_base']>upp)

In [105]:
df['wheel_base'] = np.where(cond,df['wheel_base'].mean(),df['wheel_base'])

In [106]:
df[(df['wheel_base'] < low)|(df['wheel_base']>upp)]

Empty DataFrame
Columns: [make, fuel_type, aspiration, num_of_doors, body_style, drive_wheels, engine_location, wheel_base, length, width, height, curb_weight, engine_type, num_of_cylinders, engine_size, fuel_system, compression_ratio, horsepower, peak_rpm, city_mpg, highway_mpg, price]
Index: []

[0 rows x 22 columns]

In [157]:
q1 = df['peak_rpm'].quantile(0.25)

In [158]:
q3 = df['peak_rpm'].quantile(0.75)

In [159]:
iqr = q3 - q1

In [160]:
low = q1 - 1.5*iqr
upp = q3 + 1.5*iqr

In [161]:
df[(df['peak_rpm'] < low)|(df['peak_rpm']>upp)]

make fuel_type aspiration num_of_doors body_style drive_wheels  \
165  toyota       gas        std          two      sedan          rwd   
166  toyota       gas        std          two  hatchback          rwd   

    engine_location  wheel_base  length  width  ...  engine_type  \
165           front        94.5   168.7   64.0  ...         dohc   
166           front        94.5   168.7   64.0  ...         dohc   

     num_of_cylinders engine_size fuel_system  compression_ratio horsepower  \
165              four        98.0        mpfi                9.4        112   
166              four        98.0        mpfi                9.4        112   

     peak_rpm city_mpg  highway_mpg  price  
165    6600.0       26           29   9298  
166    6600.0       26           29   9538  

[2 rows x 22 columns]

In [163]:
cond = (df['peak_rpm'] < low)|(df['peak_rpm']>upp)
df['peak_rpm'] = np.where(cond,df['peak_rpm'].mean(),df['peak_rpm'])
df[(df['peak_rpm'] < low)|(df['peak_rpm']>upp)]

Empty DataFrame
Columns: [make, fuel_type, aspiration, num_of_doors, body_style, drive_wheels, engine_location, wheel_base, length, width, height, curb_weight, engine_type, num_of_cylinders, engine_size, fuel_system, compression_ratio, horsepower, peak_rpm, city_mpg, highway_mpg, price]
Index: []

[0 rows x 22 columns]

In [167]:
q1 = df['horsepower'].quantile(0.25)
q3 = df['horsepower'].quantile(0.75)
iqr = q3 - q1
low = q1 - 1.5*iqr
upp = q3 + 1.5*iqr
df[(df['horsepower'] < low)|(df['horsepower']>upp)]

make fuel_type aspiration num_of_doors   body_style drive_wheels  \
49    jaguar       gas        std          two        sedan          rwd   
105   nissan       gas      turbo          two    hatchback          rwd   
126  porsche       gas        std          two      hardtop          rwd   
127  porsche       gas        std          two      hardtop          rwd   
128  porsche       gas        std          two  convertible          rwd   
129  porsche       gas        std          two    hatchback          rwd   

    engine_location  wheel_base  length  width  ...  engine_type  \
49            front       102.0   191.7   70.6  ...         ohcv   
105           front        91.3   170.7   67.9  ...         ohcv   
126            rear        89.5   168.9   65.0  ...         ohcf   
127            rear        89.5   168.9   65.0  ...         ohcf   
128            rear        89.5   168.9   65.0  ...         ohcf   
129           front        98.4   175.7   72.3  ...        dohcv   

     num_of_cylinders engine_size fuel_system  compression_ratio horsepower  \
49             twelve       326.0        mpfi               11.5      262.0   
105               six       181.0        mpfi                7.8      200.0   
126               six       194.0        mpfi                9.5      207.0   
127               six       194.0        mpfi                9.5      207.0   
128               six       194.0        mpfi                9.5      207.0   
129             eight       203.0        mpfi               10.0      288.0   

     peak_rpm  city_mpg  highway_mpg    price  
49     5000.0        13           17    36000  
105    5200.0        17           23    19699  
126    5900.0        17           25    32528  
127    5900.0        17           25    34028  
128    5900.0        17           25    37028  
129    5750.0        17           28  10270.0  

[6 rows x 22 columns]

In [169]:
cond = (df['horsepower'] < low)|(df['horsepower']>upp)
df['horsepower'] = np.where(cond,df['horsepower'].median(),df['horsepower'])
df[(df['horsepower'] < low)|(df['horsepower']>upp)]

Empty DataFrame
Columns: [make, fuel_type, aspiration, num_of_doors, body_style, drive_wheels, engine_location, wheel_base, length, width, height, curb_weight, engine_type, num_of_cylinders, engine_size, fuel_system, compression_ratio, horsepower, peak_rpm, city_mpg, highway_mpg, price]
Index: []

[0 rows x 22 columns]

In [171]:
q1 = df['city_mpg'].quantile(0.25)
q3 = df['city_mpg'].quantile(0.75)
iqr = q3 - q1
low = q1 - 1.5*iqr
upp = q3 + 1.5*iqr
df[(df['city_mpg'] < low)|(df['city_mpg']>upp)]

make fuel_type aspiration num_of_doors body_style drive_wheels  \
18  chevrolet       gas        std          two  hatchback          fwd   
30      honda       gas        std          two  hatchback          fwd   

   engine_location  wheel_base  length  width  ...  engine_type  \
18           front        88.4   141.1   60.3  ...            l   
30           front        86.6   144.6   63.9  ...          ohc   

    num_of_cylinders engine_size fuel_system  compression_ratio horsepower  \
18             three        61.0        2bbl                9.5       48.0   
30              four        92.0        1bbl                9.6       58.0   

    peak_rpm  city_mpg  highway_mpg  price  
18    5100.0        47           53   5151  
30    4800.0        49           54   6479  

[2 rows x 22 columns]

In [172]:
cond = (df['city_mpg'] < low)|(df['city_mpg']>upp)
df['city_mpg'] = np.where(cond,df['city_mpg'].median(),df['city_mpg'])
df[(df['city_mpg'] < low)|(df['city_mpg']>upp)]

Empty DataFrame
Columns: [make, fuel_type, aspiration, num_of_doors, body_style, drive_wheels, engine_location, wheel_base, length, width, height, curb_weight, engine_type, num_of_cylinders, engine_size, fuel_system, compression_ratio, horsepower, peak_rpm, city_mpg, highway_mpg, price]
Index: []

[0 rows x 22 columns]

In [174]:
q1 = df['highway_mpg'].quantile(0.25)
q3 = df['highway_mpg'].quantile(0.75)
iqr = q3 - q1
low = q1 - 1.5*iqr
upp = q3 + 1.5*iqr
df[(df['highway_mpg'] < low)|(df['highway_mpg']>upp)]

make fuel_type aspiration num_of_doors body_style drive_wheels  \
18  chevrolet       gas        std          two  hatchback          fwd   
30      honda       gas        std          two  hatchback          fwd   
90     nissan    diesel        std          two      sedan          fwd   

   engine_location  wheel_base  length  width  ...  engine_type  \
18           front        88.4   141.1   60.3  ...            l   
30           front        86.6   144.6   63.9  ...          ohc   
90           front        94.5   165.3   63.8  ...          ohc   

    num_of_cylinders engine_size fuel_system  compression_ratio horsepower  \
18             three        61.0        2bbl                9.5       48.0   
30              four        92.0        1bbl                9.6       58.0   
90              four       103.0         idi               21.9       55.0   

    peak_rpm  city_mpg  highway_mpg  price  
18    5100.0      24.0           53   5151  
30    4800.0      24.0           54   6479  
90    4800.0      45.0           50   7099  

[3 rows x 22 columns]

In [175]:
cond = (df['highway_mpg'] < low)|(df['highway_mpg']>upp)
df['highway_mpg'] = np.where(cond,df['highway_mpg'].median(),df['highway_mpg'])
df[(df['highway_mpg'] < low)|(df['highway_mpg']>upp)]

Empty DataFrame
Columns: [make, fuel_type, aspiration, num_of_doors, body_style, drive_wheels, engine_location, wheel_base, length, width, height, curb_weight, engine_type, num_of_cylinders, engine_size, fuel_system, compression_ratio, horsepower, peak_rpm, city_mpg, highway_mpg, price]
Index: []

[0 rows x 22 columns]

In [182]:
q1 = df['price'].quantile(0.25)
q3 = df['price'].quantile(0.75)
iqr = q3 - q1
low = q1 - 1.5*iqr
upp = q3 + 1.5*iqr
df[(df['price'] < low)|(df['price']>upp)]

make fuel_type aspiration num_of_doors   body_style  \
15             bmw       gas        std         four        sedan   
16             bmw       gas        std          two        sedan   
17             bmw       gas        std         four        sedan   
48          jaguar       gas        std         four        sedan   
49          jaguar       gas        std          two        sedan   
70   mercedes-benz    diesel      turbo         four        sedan   
71   mercedes-benz       gas        std         four        sedan   
72   mercedes-benz       gas        std          two  convertible   
73   mercedes-benz       gas        std         four        sedan   
74   mercedes-benz       gas        std          two      hardtop   
126        porsche       gas        std          two      hardtop   
127        porsche       gas        std          two      hardtop   
128        porsche       gas        std          two  convertible   

    drive_wheels engine_location  wheel_base  length  width  ...  engine_type  \
15           rwd           front  103.500000   189.0   66.9  ...          ohc   
16           rwd           front  103.500000   193.8   67.9  ...          ohc   
17           rwd           front  110.000000   197.0   70.9  ...          ohc   
48           rwd           front  113.000000   199.6   69.6  ...         dohc   
49           rwd           front  102.000000   191.7   70.6  ...         ohcv   
70           rwd           front   98.770926   202.6   71.7  ...          ohc   
71           rwd           front   98.770926   202.6   71.7  ...         ohcv   
72           rwd           front   96.600000   180.3   70.5  ...         ohcv   
73           rwd           front   98.770926   208.1   71.7  ...         ohcv   
74           rwd           front  112.000000   199.2   72.0  ...         ohcv   
126          rwd            rear   89.500000   168.9   65.0  ...         ohcf   
127          rwd            rear   89.500000   168.9   65.0  ...         ohcf   
128          rwd            rear   89.500000   168.9   65.0  ...         ohcf   

     num_of_cylinders engine_size fuel_system  compression_ratio horsepower  \
15                six       209.0        mpfi                8.0      182.0   
16                six       209.0        mpfi                8.0      182.0   
17                six       209.0        mpfi                8.0      182.0   
48                six       258.0        mpfi                8.1      176.0   
49             twelve       326.0        mpfi               11.5       95.0   
70               five       183.0         idi               21.5      123.0   
71              eight       234.0        mpfi                8.3      155.0   
72              eight       234.0        mpfi                8.3      155.0   
73              eight       308.0        mpfi                8.0      184.0   
74              eight       304.0        mpfi                8.0      184.0   
126               six       194.0        mpfi                9.5       95.0   
127               six       194.0        mpfi                9.5       95.0   
128               six       194.0        mpfi                9.5       95.0   

     peak_rpm  city_mpg  highway_mpg    price  
15     5400.0      16.0         22.0  30760.0  
16     5400.0      16.0         22.0  41315.0  
17     5400.0      15.0         20.0  36880.0  
48     4750.0      15.0         19.0  35550.0  
49     5000.0      13.0         17.0  36000.0  
70     4350.0      22.0         25.0  31600.0  
71     4750.0      16.0         18.0  34184.0  
72     4750.0      16.0         18.0  35056.0  
73     4500.0      14.0         16.0  40960.0  
74     4500.0      14.0         16.0  45400.0  
126    5900.0      17.0         25.0  32528.0  
127    5900.0      17.0         25.0  34028.0  
128    5900.0      17.0         25.0  37028.0  

[13 rows x 22 columns]

## Transformation

In [183]:
df['wheel_base'].mean(),df['wheel_base'].median()

(98.49879309010473, 97.0)

In [184]:
df['length'].mean(),df['length'].median()

(174.04926829268288, 173.2)

In [185]:
df['engine_size'].mean(),df['engine_size'].median()

(127.17115794458915, 120.0)

## Type casting

In [188]:
df['wheel_base'] = df['wheel_base'].astype('float32')

In [190]:
df['highway_mpg'] = df['highway_mpg'].astype('float32')

In [192]:
df['horsepower'] = df['horsepower'].astype('float32')

In [193]:
df['engine_size'] = df['engine_size'].astype('float32')

In [194]:
df.dtypes

make                  object
fuel_type             object
aspiration            object
num_of_doors          object
body_style            object
drive_wheels          object
engine_location       object
wheel_base           float32
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
num_of_cylinders      object
engine_size          float32
fuel_system           object
compression_ratio    float64
horsepower           float32
peak_rpm             float64
city_mpg             float64
highway_mpg          float32
price                float64
dtype: object

## variance

In [216]:
df['price'].value_counts()

price
10270.0    7
7295.0     2
8495.0     2
5572.0     2
7775.0     2
          ..
45400.0    1
16503.0    1
5389.0     1
6189.0     1
22625.0    1
Name: count, Length: 184, dtype: int64

## Dummy variables

In [217]:
df.head()

make fuel_type aspiration num_of_doors   body_style drive_wheels  \
0  alfa-romero       gas        std          two  convertible          rwd   
1  alfa-romero       gas        std          two  convertible          rwd   
2  alfa-romero       gas        std          two    hatchback          rwd   
3         audi       gas        std         four        sedan          fwd   
4         audi       gas        std         four        sedan          4wd   

  engine_location  wheel_base  length  width  ...  engine_type  \
0           front   88.599998   168.8   64.1  ...         dohc   
1           front   88.599998   168.8   64.1  ...         dohc   
2           front   94.500000   171.2   65.5  ...         ohcv   
3           front   99.800003   176.6   66.2  ...          ohc   
4           front   99.400002   176.6   66.4  ...          ohc   

   num_of_cylinders engine_size fuel_system  compression_ratio horsepower  \
0              four       130.0        mpfi                9.0      111.0   
1              four       130.0        mpfi                9.0      111.0   
2               six       152.0        mpfi                9.0      154.0   
3              four       109.0        mpfi               10.0      102.0   
4              five       136.0        mpfi                8.0      115.0   

   peak_rpm  city_mpg  highway_mpg    price  
0    5000.0      21.0         27.0  13495.0  
1    5000.0      21.0         27.0  16500.0  
2    5000.0      19.0         26.0  16500.0  
3    5500.0      24.0         30.0  13950.0  
4    5500.0      18.0         22.0  17450.0  

[5 rows x 22 columns]

In [218]:
def doors(n):
    if n == 'two':
        return 2
    else :
        return 4

In [219]:
df['num_of_doors'] = df['num_of_doors'].apply(doors)

In [234]:
def aspirat(n):
    if n == 'std':
        return 0
    else :
        return 1

In [235]:
df['aspiration'] = df['aspiration'].apply(aspirat)

In [236]:
df.head()

make fuel_type  aspiration  num_of_doors   body_style drive_wheels  \
0  alfa-romero       gas           0             2  convertible          rwd   
1  alfa-romero       gas           0             2  convertible          rwd   
2  alfa-romero       gas           0             2    hatchback          rwd   
3         audi       gas           0             4        sedan          fwd   
4         audi       gas           0             4        sedan          4wd   

  engine_location  wheel_base  length  width  ...  engine_type  \
0           front   88.599998   168.8   64.1  ...         dohc   
1           front   88.599998   168.8   64.1  ...         dohc   
2           front   94.500000   171.2   65.5  ...         ohcv   
3           front   99.800003   176.6   66.2  ...          ohc   
4           front   99.400002   176.6   66.4  ...          ohc   

   num_of_cylinders engine_size fuel_system  compression_ratio horsepower  \
0              four       130.0        mpfi                9.0      111.0   
1              four       130.0        mpfi                9.0      111.0   
2               six       152.0        mpfi                9.0      154.0   
3              four       109.0        mpfi               10.0      102.0   
4              five       136.0        mpfi                8.0      115.0   

   peak_rpm  city_mpg  highway_mpg    price  
0    5000.0      21.0         27.0  13495.0  
1    5000.0      21.0         27.0  16500.0  
2    5000.0      19.0         26.0  16500.0  
3    5500.0      24.0         30.0  13950.0  
4    5500.0      18.0         22.0  17450.0  

[5 rows x 22 columns]

## Discretization

In [237]:
df.head()

make fuel_type  aspiration  num_of_doors   body_style drive_wheels  \
0  alfa-romero       gas           0             2  convertible          rwd   
1  alfa-romero       gas           0             2  convertible          rwd   
2  alfa-romero       gas           0             2    hatchback          rwd   
3         audi       gas           0             4        sedan          fwd   
4         audi       gas           0             4        sedan          4wd   

  engine_location  wheel_base  length  width  ...  engine_type  \
0           front   88.599998   168.8   64.1  ...         dohc   
1           front   88.599998   168.8   64.1  ...         dohc   
2           front   94.500000   171.2   65.5  ...         ohcv   
3           front   99.800003   176.6   66.2  ...          ohc   
4           front   99.400002   176.6   66.4  ...          ohc   

   num_of_cylinders engine_size fuel_system  compression_ratio horsepower  \
0              four       130.0        mpfi                9.0      111.0   
1              four       130.0        mpfi                9.0      111.0   
2               six       152.0        mpfi                9.0      154.0   
3              four       109.0        mpfi               10.0      102.0   
4              five       136.0        mpfi                8.0      115.0   

   peak_rpm  city_mpg  highway_mpg    price  
0    5000.0      21.0         27.0  13495.0  
1    5000.0      21.0         27.0  16500.0  
2    5000.0      19.0         26.0  16500.0  
3    5500.0      24.0         30.0  13950.0  
4    5500.0      18.0         22.0  17450.0  

[5 rows x 22 columns]

In [238]:
def aspi(n):
    if n == 0:
        return 'std'
    else :
        return 'turbo'

In [239]:
df['aspiration'] = df['aspiration'].apply(aspi)

In [240]:
df.head()

make fuel_type aspiration  num_of_doors   body_style drive_wheels  \
0  alfa-romero       gas        std             2  convertible          rwd   
1  alfa-romero       gas        std             2  convertible          rwd   
2  alfa-romero       gas        std             2    hatchback          rwd   
3         audi       gas        std             4        sedan          fwd   
4         audi       gas        std             4        sedan          4wd   

  engine_location  wheel_base  length  width  ...  engine_type  \
0           front   88.599998   168.8   64.1  ...         dohc   
1           front   88.599998   168.8   64.1  ...         dohc   
2           front   94.500000   171.2   65.5  ...         ohcv   
3           front   99.800003   176.6   66.2  ...          ohc   
4           front   99.400002   176.6   66.4  ...          ohc   

   num_of_cylinders engine_size fuel_system  compression_ratio horsepower  \
0              four       130.0        mpfi                9.0      111.0   
1              four       130.0        mpfi                9.0      111.0   
2               six       152.0        mpfi                9.0      154.0   
3              four       109.0        mpfi               10.0      102.0   
4              five       136.0        mpfi                8.0      115.0   

   peak_rpm  city_mpg  highway_mpg    price  
0    5000.0      21.0         27.0  13495.0  
1    5000.0      21.0         27.0  16500.0  
2    5000.0      19.0         26.0  16500.0  
3    5500.0      24.0         30.0  13950.0  
4    5500.0      18.0         22.0  17450.0  

[5 rows x 22 columns]

## scaling

In [223]:
#norm
def norm(x):
    n = (x - x.min())/(x.max() - x.min())
    return n

In [224]:
norm(df['wheel_base'])

0      0.072464
1      0.072464
2      0.286232
3      0.478261
4      0.463768
         ...   
200    0.815217
201    0.815217
202    0.815217
203    0.815217
204    0.815217
Name: wheel_base, Length: 205, dtype: float32

In [228]:
#standard
def stnd(x):
    n = (x - x.mean())/(x.std())
    return n

In [230]:
stnd(df['price'])

0      0.070332
1      0.458656
2      0.458656
3      0.129130
4      0.581421
         ...   
200    0.503239
201    0.787537
202    1.102848
203   -0.346422
204    1.250166
Name: price, Length: 205, dtype: float64

In [232]:
df['aspiration'].value_counts()

aspiration
std      168
turbo     37
Name: count, dtype: int64