# pandas Series
1. Create pandas series with different `data types` in `different ways`
2. Find the `attributes` of Series of [10,30,40,1,3,6,14,18,23] with index starts from `100`
3. create salaries of `30 employee salaries randomly from 30000-90000` then `measure and describe` the data using pandas series.
4. What are the `similaraties` and `differences` between pandas series and nnumpy array.Prove it with code.
5. create pandas series with ranges from 100 to 150 then apply indexing and slicing on it.

1. Create pandas series with different data types in different ways

In [6]:
#from list
num = list(range(1,11))
num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
import pandas as pd
pd.Series(num)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [8]:
#from tuple
tup1 = ('laxman','uday','sathish','venky','charan')
pd.Series(tup1)

0     laxman
1       uday
2    sathish
3      venky
4     charan
dtype: object

In [9]:
#from numpy array
import numpy as np
age = np.arange(20,26)
pd.Series(age)

0    20
1    21
2    22
3    23
4    24
5    25
dtype: int32

2. Find the attributes of Series of [10,30,40,1,3,6,14,18,23] with index starts from 100

In [18]:
series = pd.Series([10,30,40,1,3,6,14,18,23],index=list(range(100,109)))
series

100    10
101    30
102    40
103     1
104     3
105     6
106    14
107    18
108    23
dtype: int64

In [19]:
series.shape

(9,)

In [24]:
series.dtype

dtype('int64')

In [25]:
series.head()

100    10
101    30
102    40
103     1
104     3
dtype: int64

In [26]:
series.tail()

104     3
105     6
106    14
107    18
108    23
dtype: int64

In [28]:
series.info()

<class 'pandas.core.series.Series'>
Index: 9 entries, 100 to 108
Series name: None
Non-Null Count  Dtype
--------------  -----
9 non-null      int64
dtypes: int64(1)
memory usage: 144.0 bytes


In [29]:
series.describe()

count     9.000000
mean     16.111111
std      13.033078
min       1.000000
25%       6.000000
50%      14.000000
75%      23.000000
max      40.000000
dtype: float64

3. create salaries of 30 employee salaries randomly from 30000-90000 then measure and describe the data using pandas series.

In [33]:
salaries = np.random.randint(30000,90000,30)
salaries= pd.Series(salaries)
salaries

0     33421
1     57230
2     88671
3     88425
4     68188
5     52564
6     74619
7     64439
8     88659
9     52049
10    74503
11    43728
12    83142
13    55177
14    79283
15    31950
16    49861
17    54275
18    70477
19    68595
20    52231
21    45121
22    58832
23    79106
24    47138
25    72576
26    48481
27    48045
28    68891
29    64607
dtype: int32

In [34]:
salaries.describe()

count       30.000000
mean     62142.800000
std      15872.429826
min      31950.000000
25%      50408.000000
50%      61635.500000
75%      74021.250000
max      88671.000000
dtype: float64

In [35]:
salaries.info()

<class 'pandas.core.series.Series'>
RangeIndex: 30 entries, 0 to 29
Series name: None
Non-Null Count  Dtype
--------------  -----
30 non-null     int32
dtypes: int32(1)
memory usage: 252.0 bytes


4. What are the similaraties and differences between pandas series and nnumpy array.Prove it with code.

In [43]:
n = np.array([1,23,4,5,6,7])
n

array([ 1, 23,  4,  5,  6,  7])

In [44]:
n[1]

23

In [45]:
n[1:6]

array([23,  4,  5,  6,  7])

In [52]:
n*2

array([ 2, 46,  8, 10, 12, 14])

In [46]:
p = pd.Series([1,23,3,4,12,13],index = ['a','b','c','d','e','f'])
p

a     1
b    23
c     3
d     4
e    12
f    13
dtype: int64

In [48]:
p['a']

1

In [50]:
p['a':'e']

a     1
b    23
c     3
d     4
e    12
dtype: int64

In [51]:
p*2

a     2
b    46
c     6
d     8
e    24
f    26
dtype: int64

5. create pandas series with ranges from 100 to 150 then apply indexing and slicing on it.

In [53]:
r = np.arange(100,150)
r = pd.Series(r)
r

0     100
1     101
2     102
3     103
4     104
5     105
6     106
7     107
8     108
9     109
10    110
11    111
12    112
13    113
14    114
15    115
16    116
17    117
18    118
19    119
20    120
21    121
22    122
23    123
24    124
25    125
26    126
27    127
28    128
29    129
30    130
31    131
32    132
33    133
34    134
35    135
36    136
37    137
38    138
39    139
40    140
41    141
42    142
43    143
44    144
45    145
46    146
47    147
48    148
49    149
dtype: int32

In [54]:
r[0]

100

In [56]:
r[12]

112

In [57]:
r[20:30]

20    120
21    121
22    122
23    123
24    124
25    125
26    126
27    127
28    128
29    129
dtype: int32

In [58]:
r[30:49]

30    130
31    131
32    132
33    133
34    134
35    135
36    136
37    137
38    138
39    139
40    140
41    141
42    142
43    143
44    144
45    145
46    146
47    147
48    148
dtype: int32