### Data Cleaning using numpy

**The following are the student marks of a class**
[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]



1. Find the no of outliers and missing values?
2. replace the outliers with 45 and missing value with 87.
3. what is the average marks of students after 2nd step?
4. How many students got less than 60 marks?
5. what is the maximum marks?
6. Convert the marks to float32.

In [5]:
import numpy as np

In [6]:
marks = np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53,44])

In [7]:
marks

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [9]:
np.isnan(marks).sum()

4

In [13]:
(marks>100).sum()
#no.of outliers are 3 and missing values are 4

3

In [18]:
marks = np.where(np.isnan(marks),87,marks)
marks

array([ 44.,  24.,  87.,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  87.,  87.,   3.,  56.,  81.,  59., 122.,  92.,  87.,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [20]:
marks = np.where(marks>100,45,marks)
marks

array([44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
       87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
        2., 53., 44.])

In [21]:
np.mean(marks)

56.96551724137931

In [23]:
(marks<60).sum()

18

In [25]:
marks.max()

97.0

In [28]:
marks = marks.astype('float32')
marks

array([44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
       87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
        2., 53., 44.], dtype=float32)

In [29]:
marks.dtype

dtype('float32')

### Solving Linear Equations


    
1. 2x + 3y - z = 10

    x - y + 2z = 5
    
    3x + 2y + z = 12
    
    
    
2. 2x + y - z + 3w = 8

    3x - 2y + 2z + 2w = 1
    
    x + 3y - 2z + w = 7
    
    4x - y + z - 2w = 3
   
   
   
3. 4x + 2y - 3z = 10

    -2x + 3y + z = -3
    
    x - y + 2z = 4
    
Solve the system of equations using NumPy's linalg.solve function.


In [35]:
a = np.array([[2,3,-1],[1,-1,2],[3,2,1]])
b = np.array([[10],[5],[12]])
print(a)
print(b)

[[ 2  3 -1]
 [ 1 -1  2]
 [ 3  2  1]]
[[10]
 [ 5]
 [12]]


In [36]:
np.linalg.solve(a,b)

array([[-6.75539944e+15],
       [ 6.75539944e+15],
       [ 6.75539944e+15]])

In [41]:
x = np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
y = np.array([[8],[1],[7],[3]])
print(x)
print(y)

[[ 2  1 -1  3]
 [ 3 -2  2  2]
 [ 1  3 -2  1]
 [ 4 -1  1 -2]]
[[8]
 [1]
 [7]
 [3]]


In [42]:
np.linalg.solve(x,y)

array([[ 1.73170732],
       [-0.75609756],
       [-3.46341463],
       [ 0.6097561 ]])

In [43]:
p = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
q = np.array([[10],[-3],[4]])
print(p)
print(q)

[[ 4  2 -3]
 [-2  3  1]
 [ 1 -1  2]]
[[10]
 [-3]
 [ 4]]


In [44]:
np.linalg.solve(p,q)

array([[2.85365854],
       [0.6097561 ],
       [0.87804878]])

### Conditional Selection with np.where()


1.	Generate a random 1D array A of 10 integers between 1 and 100.

2.	Use np.where() to find the indices where the elements of A are greater than 50.

3.	Create a new array B that contains elements from A where the condition is met.

4.	Calculate the mean of array B and print it along with arrays A and B.

In [60]:
A = np.random.randint(1,100,10)
A

array([59, 56, 63, 17, 75, 17, 26, 72, 37, 66])

In [61]:
A

array([59, 56, 63, 17, 75, 17, 26, 72, 37, 66])

In [65]:
np.where(A>50)

(array([0, 1, 2, 4, 7, 9], dtype=int64),)

In [66]:
B = A[np.where(A>50)]
B

array([59, 56, 63, 75, 72, 66])

In [75]:
print(B.mean(),'\n',A,'\n',B)

65.16666666666667 
 [59 56 63 17 75 17 26 72 37 66] 
 [59 56 63 75 72 66]


### Replace Values with np.where()

1.	Create a 4x4 random integer matrix C with values between -10 and 10.

2.	Use np.where() to replace all negative values in matrix C with 0.

3.	Print the original matrix C and the modified matrix.

In [93]:
c = np.random.randint(-10,10,size = (4,4))

In [92]:
modified = np.where(c<0,0,c)

In [97]:
print(c)

[[ 5 -7  0 -7]
 [ 6  4  3  8]
 [-8 -6 -9  9]
 [ 5 -1  3 -4]]


In [96]:
print(modified)

[[1 8 0 0]
 [0 0 0 0]
 [8 8 0 5]
 [2 0 0 3]]
