**Creation of ndarray**

1. Write python code to create 3d array in different ways with 15 elements.
2. Array Creation:
a. Create a 4D NumPy array containing the first 12 positive integers as arr1.
b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.
3. Find all attributes of array1 and array2
4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.


**Array Slicing and Indexing:**

a. Creating Arrays:
      - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
      - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
 b.Basic Indexing:
      - Print the element at index 3 of  arr1.
      - Print the element at row 2, column 1 of  arr2

   c. Array Slicing:
      - Print the first five elements of `arr1`.
      - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
       - Print every second element starting from index 1 up to index 7 of `arr1`.







**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      - Convert the `float_array` to an array with data type `int32`. Print the result.
      - Convert the `int_array` to an array with data type `float32`. Print the result.

**Generating Random Numbers:**

1.	Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.	Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.	Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.	Apply descriptive statistics for rand_matrix.


**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:
1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?



**Creation of ndarray**

1. Write python code to create 3d array in different ways with 15 elements.
2. Array Creation:

a. Create a 4D NumPy array containing the first 12 positive integers as arr1.

b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.

3. Find all attributes of array1 and array2
4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.


In [1]:
import numpy as np

In [5]:
np.arange(1,16).reshape(1,3,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [6]:
np.array([[[1,  2,  3,  4,  5],[ 6,  7,  8,  9, 10],[11, 12, 13, 14, 15]]])

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [7]:
np.arange(1,16).reshape(1,5,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]])

In [9]:
np.arange(1,16).reshape(1,1,15)

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [10]:
np.arange(1,16).reshape(1,15,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]]])

In [11]:
np.arange(1,16).reshape(15,1,1)

array([[[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]]])

In [13]:
##Array Creation:
arr1 = np.array([[[[1,2,3],[4,5,6],[7,8,9,],[10,11,12]]]])

In [15]:
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [21]:
array1 = np.random.randint(0,1,20).reshape(1,4,5)
array1

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [47]:
#Find all attributes of array1 and array2

In [48]:
#array1
arr1.dtype

dtype('int32')

In [29]:
arr1.itemsize

4

In [35]:
arr1.size

12

In [36]:
arr1.nbytes

48

In [37]:
arr1.ndim

4

In [50]:
#array2
array1.dtype

dtype('int32')

In [51]:
array1.ndim

3

In [52]:
array1.size

20

In [53]:
array1.nbytes

80

In [54]:
array1.itemsize

4

In [58]:
#Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

In [60]:
arr1

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [63]:
np.mean(arr1)

6.5

In [64]:
np.median(arr1)

6.5

In [65]:
np.max(arr1)

12

In [66]:
np.min(arr1)

1

In [69]:
range1 = np.max(arr1)-np.min(arr1)
range1

11

In [70]:
np.var(arr1)

11.916666666666666

In [71]:
np.std(arr1)

3.452052529534663

In [72]:
Q1 = np.percentile(arr1,25)
Q3 = np.percentile(arr1,75) 
IQR = Q3-Q1
low = Q1 - (1.5*IQR)
upp = Q3 + (1.5*IQR)

In [73]:
IQR

5.5

In [74]:
low

-4.5

In [75]:
upp

17.5

In [77]:
arr1[(arr1<low)|(arr1>upp)]

array([], dtype=int32)

**Array Slicing and Indexing:**

a. Creating Arrays:
      
   - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
      
   - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
 b.Basic Indexing:
      
   - Print the element at index 3 of  arr1.
      
   - Print the element at row 2, column 1 of  arr2

   c. Array Slicing:
      
   - Print the first five elements of `arr1`.
      
   - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
     
   - Print every second element starting from index 1 up to index 7 of `arr1`.

In [80]:
arr1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
arr1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [83]:
arr2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
arr1[3]

73

In [90]:
arr2[1,0]

3

In [92]:
arr1[:5]

array([ 0, 11, 26, 73, 42])

In [93]:
arr2[1:,:2]

array([[3, 4],
       [6, 7]])

In [96]:
arr1[1:7:2]

array([11, 73, 51])

**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      
   - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      
   - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      
   - Convert the `float_array` to an array with data type `int32`. Print the result.
      
   - Convert the `int_array` to an array with data type `float32`. Print the result.


In [104]:
int_array = np.array([1, 2, 3, 4, 5],dtype="int16")
int_array

array([1, 2, 3, 4, 5], dtype=int16)

In [105]:
int_array.dtype

dtype('int16')

In [101]:
float_array = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
float_array

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [102]:
float_array.dtype

dtype('float64')

In [106]:
f = float_array.astype("int32")
print(f)

[0 0 0 0 0]


In [107]:
f.dtype

dtype('int32')

In [108]:
i = int_array.astype("float32")
print(i)

[1. 2. 3. 4. 5.]


In [109]:
i.dtype

dtype('float32')


**Generating Random Numbers:**

1. Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2. Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3. Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4. Apply descriptive statistics for rand_matrix.

In [120]:
rand_integers = np.random.randint(0,101,10)
rand_integers

array([22, 24, 65,  2, 57,  9, 78, 25, 94,  9])

In [114]:
rand_uniform = np.random.uniform(-1,1,5)
rand_uniform

array([-0.9315225 , -0.89300978, -0.14553273,  0.71802218,  0.89768846])

In [124]:
rand_matrix = np.random.randint(50,101,16).reshape(4,4)
rand_matrix

array([[ 92,  78,  66, 100],
       [ 65,  66,  51,  88],
       [ 93,  97,  92,  65],
       [ 78,  56,  66,  54]])

In [128]:
np.mean(rand_matrix)

75.4375

In [127]:
np.median(rand_matrix)

72.0

In [129]:
range1 = np.max(rand_matrix)-np.min(rand_matrix)
range1

49

In [130]:
np.var(rand_matrix)

250.99609375

In [131]:
np.std(rand_matrix)

15.842856237118356

In [132]:
Q1 = np.percentile(rand_matrix,25)
Q3 = np.percentile(rand_matrix,75) 
IQR = Q3-Q1
low = Q1 - (1.5*IQR)
upp = Q3 + (1.5*IQR)

In [133]:
IQR

27.0

In [134]:
low

24.5

In [135]:
upp

132.5

In [136]:
rand_matrix[(rand_matrix < low)|(rand_matrix > upp)]

array([], dtype=int32)

**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:

1.	How many employees are getting less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?



In [138]:
Salaries = np.array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638])


In [141]:
Salaries[Salaries<50000]

array([31250, 39828, 41671, 34225, 32199])

In [140]:
emp = Salaries[Salaries<50000]
emp.size

5

In [142]:
np.median(Salaries)

61699.5

In [163]:
#it is not following Normal Distribution because mean and median values not closed values

In [144]:
range1 = np.max(Salaries)-np.min(Salaries)
range1

3082388

In [157]:
a= np.mean(Salaries)
a

166169.16666666666

In [147]:
Q1 = np.percentile(Salaries,25)
Q3 = np.percentile(Salaries,75) 
IQR = Q3-Q1

In [181]:
Salaries[(Salaries<a)&(Salaries>Q3)]

array([87877, 85051, 94868, 98446, 99658, 89224, 90947])

In [149]:
Q1

52963.25

In [166]:
Q3

84496.5

In [174]:
emp = Salaries[Salaries<52963.25]
emp

array([52453, 31250, 39828, 41671, 51428, 50477, 34225, 32199])

In [175]:
emp.size

8

In [173]:
len(Salaries[Salaries<52963.25])

8

In [176]:
np.std(Salaries)

547678.585700353

In [177]:
np.max(Salaries)

3113638

In [178]:
np.min(Salaries)

31250